### ISSUE TITLE
Title not centered in navBar in Android with one of left/right icons

### ISSUE THREAD

**Issue by iuraya** [RNRF/react-native-router-flux#2467] opened 2017-10-06 16:59 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.1

### Expected behaviour
Title appears correctly centered when neither left and right icons exists or when both of them exist
With just one of left or right icons at the same time title should appear centered

### Actual behaviour
The title is not centered if only one of right and left icons exists at the same time.

<img width="390" alt="captura de pantalla 2017-10-06 a las 16 47 20" src="https://user-images.githubusercontent.com/14769734/31289237-63b3e1c8-aac8-11e7-9ffb-1c262f748e0a.png">

**Comment by JessieYF** [comment] 2017-10-11 03:08
I encountered this issue as well. What I do is adding a placeholder for left button and right button on root Scene. When the child Scene has any left/right button, override the property.

```
renderPlaceholder = () => <View />
<Scene
     key="root"
     renderLeftButton={this.renderPlaceholder}
     renderRightButton={this.renderPlaceholder}
/ >
```

eg: child Scene
```
<Scene
     key="sub"
     title="sub"
     component={PageComponent}
     hideTabBar
     renderLeftButton={() => <BackButton />}
/>
```

**Comment by aksonov** [comment] 2017-10-17 11:03
Please check latest master and PR #2491 (I've just merged it). Unfortunately I'm working on ios app only.

**Comment by daviscabral** [comment] 2017-12-06 14:17
@aksonov I can help you testing changes on android - just tag me in the PR and give me instructions and I can check it there. :+1:

**Comment by aksonov** [comment] 2017-12-06 14:19
@daviscabral Could you check this ticket? :)

**Comment by sagark1510** [comment] 2017-12-18 07:05
@aksonov it's still the same on android. Do I have to add any props to scene to get reflection or it should work automatically?

**Comment by aksonov** [comment] 2018-01-05 09:59
Right, I see this bug and PR is welcome.

**Comment by PiotrKujawa** [comment] 2018-01-05 11:01
<img width="403" alt="android_title_alignment" src="https://user-images.githubusercontent.com/4909699/34606549-2809f95c-f210-11e7-80d8-f13b9b469735.png">

**Comment by Albinzr** [comment] 2018-01-25 10:33
Will this be fixed?,I cant push the app to production without a fix.

**Comment by kamranyounis12** [comment] 2018-02-20 08:55
@daviscabral  any update?

**Comment by daviscabral** [comment] 2018-02-23 09:35
Issue is still present on master - going to investigate now to see if I am able to solve it.
<img width="427" alt="screenshot 2018-02-23 06 34 54" src="https://user-images.githubusercontent.com/4285/36587346-ad0bc774-1863-11e8-826a-5b076cfde647.png">

**Comment by Gulci** [comment] 2018-03-15 15:52
This issue is also present on React Native v. 0.54.2 with react-native-router-flux v. 4.0.0-beta.28.

**Comment by daviscabral** [comment] 2018-04-08 10:34
I am a bit busy lately and couldn't finish the PR that I've started. I'll check if later today I'll spare some time for it. Thank you.

**Comment by daviscabral** [comment] 2018-05-12 20:27
On it - should have a PR in a few hours. I am in a company transition, things are just crazy lately.

**Comment by daviscabral** [comment] 2018-05-13 23:47
Sorry - took longer than I thought cause I was trying to fix the `Example` project that was not running - so I couldn't actually test and verify it properly.

**Comment by acollazomayer** [comment] 2018-05-14 01:32
@daviscabral Thank you! I manage to solve the issue making a custom nav bar. However this is better! Thanks!! Good luck with the company transition!

**Comment by daviscabral** [comment] 2018-05-14 01:33
Thank you. Glad to hear that.

**Comment by xbogdan** [comment] 2018-05-20 11:56
I'm still having this issues with react-native 0.55 and react-native-router-flux 4.0.0-beta.31 .
Was this fixed or should I follow @acollazomayer solution ?

**Comment by massimopibiri** [comment] 2018-05-23 09:32
The solution written by @JessieYF works good

**Comment by aksonov** [comment] 2018-08-08 15:25
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by og24715** [comment] 2018-10-09 10:47
This issue still exists with RNRF v4.0.5. Im not able to open it, but I think that it have to be open.

**Comment by aksonov** [comment] 2018-10-09 10:48
cc @daviscabral

**Comment by daviscabral** [comment] 2018-10-11 19:52
> Fixed on #3256.
> 
> [![Image from Gyazo](https://camo.githubusercontent.com/9d67376b43d915a2a6b3da600e5154cc9a7e318c/68747470733a2f2f692e6779617a6f2e636f6d2f38343939306530343335366564333837636562353063613939643434386135612e676966)](https://gyazo.com/84990e04356ed387ceb50ca99d448a5a)

This was possible because of react-navigation changes,  when `headerLayoutPreset` support was added. Docs were also updated to reflect it. 

`Example.js` file has an example of how to make it work, below the line where it happens:

```
<Stack key="customNavBar" hideTabBar headerLayoutPreset='center'>
```

**Closed by daviscabral** 2018-10-11 19:52 UTC
Labels: bug, help wanted
